services:
  lingdrama:
    image: lingdrama:local
    container_name: lingdrama
    build: .
    ports:
      - "5679:5679"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5679
      - DB_PATH=/app/data/lingdrama.db
      - STORAGE_PATH=/app/data/static
    restart: unless-stopped
